name: ML CI/CD Pipeline

on:
  push:
    branches:
      - main
  
env:
  AZURE_WEBAPP_NAME: BitsAssignmentGroup73
  AZURE_WEBAPP_PACKAGE_PATH: models/

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          pip install flake8
      - name: Run linter
        run: |
          flake8 src/
            
  testing:
    runs-on: ubuntu-latest
    needs: linting
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest
      - name: Train model
        run: |
          python src/train.py
      - name: Test model
        run: |
          pytest tests/
      - name: Save model artifact
        uses: actions/upload-artifact@v3
        with:
          name: trained-model
          path: models/

  deployment:
    runs-on: ubuntu-latest
    needs: testing
    steps:
      - name: Echo variables for debugging
        run: |
         echo "App Name: ${{ env.AZURE_WEBAPP_NAME }}"
         echo "Publish Profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}"
         echo "Package Path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}"
      - name: Download model artifact
        uses: actions/download-artifact@v3
        with:
          name: trained-model
          path: models/
      - name: Deployment
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          package: "${{ env.AZURE_WEBAPP_PACKAGE_PATH }}"
      - name: Deploy model
        run: |
          echo "Model deployed successfully to dummy endpoint!"
