name: ML CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          pip install flake8
      - name: Run linter
        run: |
          flake8 src/
            
  testing:
    runs-on: ubuntu-latest
    needs: linting
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest
      - name: Run tests
        run: |
          pytest tests/
      - name: Train model
        run: |
          python src/train.py
      - name: Save model artifact
        uses: actions/upload-artifact@v2
        with:
          name: trained-model
          path: models/

  deployment:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download model artifact
        uses: actions/download-artifact@v2
        with:
          name: trained-model
          path: models/
      - name: Deploy model
        run: |
          python src/deploy_model.py
          echo "Model deployed successfully to dummy endpoint!"
