name: ML CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          pip install flake8
      - name: Run linter
        run: |
          flake8 src/
          
  training:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Train the model
        run: python src/train.py
  store-model:
    runs-on: ubuntu-latest
    needs: training
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Add the model to the repository
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add model.pkl
          git commit -m "Add trained model"
          git push

  testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest
      - name: Run tests
        run: |
          pytest tests/

  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Deploy Model
        run: |
          echo "Model deployed successfully to dummy endpoint!"
